name: InfiniteObsidian
main: com.i0dev.plugin.infiniteobsidian.InfiniteObsidianPlugin
version: 2.0.2
author: i01
description: This plugin allows you to place obsidian without the stack running out, costing money every time its placed.
website: www.i0dev.com
softdepend:
  - PlaceHolderAPI
  - Factions
depend:
  - Vault
  - NBTAPI
commands:
  infiniteobsidian:
    aliases:
      - infiniteobby
      - infobby
    description: The main infinite obsidian command
    usage: /potfill [help/reload/version/give]

permissions:
  infiniteobsidian.reload:
    description: Use the /infiniteobsidian reload command.
    default: op
  infiniteobsidian.use:
    description: Use infinite obsidian blocks.
    default: not op
  infiniteobsidian.give:
    description: Use the /infiniteobsidian give command.
    default: op